// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// f1
double f1(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f1(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f1(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f10
double f10(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f10(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f10(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f11
double f11(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f11(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f11(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f12
double f12(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f12(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f12(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f13
double f13(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f13(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f13(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f14
double f14(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f14(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f14(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f15
double f15(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f15(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f15(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f16
double f16(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f16(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f16(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f17
double f17(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f17(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f17(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f18
double f18(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f18(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f18(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f19
double f19(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f19(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f19(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f2
double f2(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f2(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f2(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f20
double f20(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f20(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f20(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f21
double f21(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f21(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f21(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f22
double f22(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f22(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f22(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f23
double f23(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f23(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f23(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f24
double f24(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f24(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f24(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f25
double f25(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f25(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f25(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f26
double f26(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f26(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f26(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f27
double f27(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f27(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f27(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f28
double f28(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f28(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f28(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f29
double f29(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f29(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f29(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f3
double f3(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f3(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f3(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f30
double f30(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f30(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f30(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f31
double f31(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f31(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f31(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f32
double f32(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f32(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f32(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f33
double f33(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f33(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f33(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f34
double f34(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f34(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f34(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f35
double f35(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f35(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f35(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f36
double f36(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f36(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f36(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f4
double f4(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f4(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f4(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f5
double f5(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f5(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f5(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f6
double f6(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f6(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f6(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f7
double f7(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f7(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f7(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f8
double f8(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f8(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f8(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}
// f9
double f9(double q12, double q23, double q34, double q45, double q56, double q21, double q32, double q43, double q54, double q65, double b0);
RcppExport SEXP _Sigma_f9(SEXP q12SEXP, SEXP q23SEXP, SEXP q34SEXP, SEXP q45SEXP, SEXP q56SEXP, SEXP q21SEXP, SEXP q32SEXP, SEXP q43SEXP, SEXP q54SEXP, SEXP q65SEXP, SEXP b0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type q12(q12SEXP);
    Rcpp::traits::input_parameter< double >::type q23(q23SEXP);
    Rcpp::traits::input_parameter< double >::type q34(q34SEXP);
    Rcpp::traits::input_parameter< double >::type q45(q45SEXP);
    Rcpp::traits::input_parameter< double >::type q56(q56SEXP);
    Rcpp::traits::input_parameter< double >::type q21(q21SEXP);
    Rcpp::traits::input_parameter< double >::type q32(q32SEXP);
    Rcpp::traits::input_parameter< double >::type q43(q43SEXP);
    Rcpp::traits::input_parameter< double >::type q54(q54SEXP);
    Rcpp::traits::input_parameter< double >::type q65(q65SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    rcpp_result_gen = Rcpp::wrap(f9(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Sigma_f1", (DL_FUNC) &_Sigma_f1, 11},
    {"_Sigma_f10", (DL_FUNC) &_Sigma_f10, 11},
    {"_Sigma_f11", (DL_FUNC) &_Sigma_f11, 11},
    {"_Sigma_f12", (DL_FUNC) &_Sigma_f12, 11},
    {"_Sigma_f13", (DL_FUNC) &_Sigma_f13, 11},
    {"_Sigma_f14", (DL_FUNC) &_Sigma_f14, 11},
    {"_Sigma_f15", (DL_FUNC) &_Sigma_f15, 11},
    {"_Sigma_f16", (DL_FUNC) &_Sigma_f16, 11},
    {"_Sigma_f17", (DL_FUNC) &_Sigma_f17, 11},
    {"_Sigma_f18", (DL_FUNC) &_Sigma_f18, 11},
    {"_Sigma_f19", (DL_FUNC) &_Sigma_f19, 11},
    {"_Sigma_f2", (DL_FUNC) &_Sigma_f2, 11},
    {"_Sigma_f20", (DL_FUNC) &_Sigma_f20, 11},
    {"_Sigma_f21", (DL_FUNC) &_Sigma_f21, 11},
    {"_Sigma_f22", (DL_FUNC) &_Sigma_f22, 11},
    {"_Sigma_f23", (DL_FUNC) &_Sigma_f23, 11},
    {"_Sigma_f24", (DL_FUNC) &_Sigma_f24, 11},
    {"_Sigma_f25", (DL_FUNC) &_Sigma_f25, 11},
    {"_Sigma_f26", (DL_FUNC) &_Sigma_f26, 11},
    {"_Sigma_f27", (DL_FUNC) &_Sigma_f27, 11},
    {"_Sigma_f28", (DL_FUNC) &_Sigma_f28, 11},
    {"_Sigma_f29", (DL_FUNC) &_Sigma_f29, 11},
    {"_Sigma_f3", (DL_FUNC) &_Sigma_f3, 11},
    {"_Sigma_f30", (DL_FUNC) &_Sigma_f30, 11},
    {"_Sigma_f31", (DL_FUNC) &_Sigma_f31, 11},
    {"_Sigma_f32", (DL_FUNC) &_Sigma_f32, 11},
    {"_Sigma_f33", (DL_FUNC) &_Sigma_f33, 11},
    {"_Sigma_f34", (DL_FUNC) &_Sigma_f34, 11},
    {"_Sigma_f35", (DL_FUNC) &_Sigma_f35, 11},
    {"_Sigma_f36", (DL_FUNC) &_Sigma_f36, 11},
    {"_Sigma_f4", (DL_FUNC) &_Sigma_f4, 11},
    {"_Sigma_f5", (DL_FUNC) &_Sigma_f5, 11},
    {"_Sigma_f6", (DL_FUNC) &_Sigma_f6, 11},
    {"_Sigma_f7", (DL_FUNC) &_Sigma_f7, 11},
    {"_Sigma_f8", (DL_FUNC) &_Sigma_f8, 11},
    {"_Sigma_f9", (DL_FUNC) &_Sigma_f9, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_Sigma(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
