# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f1 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f1`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f10 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f10`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f11 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f11`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f12 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f12`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f13 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f13`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f14 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f14`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f15 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f15`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f16 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f16`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f17 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f17`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f18 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f18`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f19 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f19`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f2 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f2`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f20 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f20`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f21 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f21`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f22 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f22`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f23 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f23`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f24 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f24`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f25 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f25`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f26 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f26`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f27 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f27`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f28 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f28`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f29 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f29`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f3 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f3`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f30 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f30`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f31 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f31`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f32 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f32`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f33 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f33`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f34 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f34`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f35 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f35`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f36 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f36`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f4 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f4`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f5 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f5`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f6 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f6`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f7 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f7`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f8 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f8`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

f9 <- function(q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0) {
    .Call(`_Sigma_f9`, q12, q23, q34, q45, q56, q21, q32, q43, q54, q65, b0)
}

